---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_paths:
    # duplicate structures in testinfra files
    - tests/
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true

ratings:
  paths:
    - "**.py"
    - "**.md"
    - "**.yml"
