---
language: python
python:
  - '2.7'

# Spin off separate builds for each of the following versions of Ansible
env:
  global:
    - MOLECULE_VERSION='1.15.0'
    - DOCKER_PY_VERSION='1.10.6'
  matrix:
    - ANSIBLE_VERSION='latest'
    - ANSIBLE_VERSION='2.2.0'
    - ANSIBLE_VERSION='2.1.0'

# Require the standard build environment
sudo: required

services:
  - docker

# Cache Ansible and Molecule to speed things up
cache:
  - pip
  - ruby
  - rvm

before_install:
  - rvm get stable --auto-dotfiles
  - rvm default
  - ruby -v
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::='--force-confold' --force-yes -y docker-engine

install:
  # Upgrade PIP
  - pip install --upgrade pip

  # Install Ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then
      pip install ansible;
    else
      pip install ansible==$ANSIBLE_VERSION;
    fi

  # Install Python API for Docker (required by Molecule Docker driver)
  - pip install docker-py==$DOCKER_PY_VERSION

  # Install Molecule
  - pip install molecule==$MOLECULE_VERSION

  # Install Ruby Bundler
  - gem install bundler

  # Install Ruby Gems from Gemfile
  - bundle install --path vendor/bundle

script:
  - bundle exec molecule test
