---
# https://giorgos.sealabs.net/docker-cache-on-travis-and-docker-112.html
sudo: required

language: python
python:
  - '2.7'

# Spin off separate builds for each of the following versions of Ansible
env:
  global:
    - MOLECULE_VERSION='1.25.0'
    - DOCKER_VERSION='2.2.1'
    - TESTINFRA_VERSION='1.6.4'
  matrix:
    - ANSIBLE_VERSION='latest'
    - ANSIBLE_VERSION='2.3.0'
    - ANSIBLE_VERSION='2.2.0'
    - ANSIBLE_VERSION='2.1.0'

services:
  - docker

install:
  - pip install --upgrade pip
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then
      pip install ansible;
    else
      pip install ansible==$ANSIBLE_VERSION;
    fi
  - ansible --version
  - pip install molecule==$MOLECULE_VERSION
  - pip install docker==$DOCKER_VERSION
  - pip install testinfra==$TESTINFRA_VERSION

script:
  - molecule test
